version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(levelname)-8s][%(pathname)s:%(lineno)s] %(message)s'
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  cloud_logging:
    class: cs.core.logger.handler.CsCloudLoggingHandler
    formatter: json
loggers:
  develop:
    level: DEBUG
    handlers: [console]
    propagate: no
  staging:
    level: INFO
    handlers: [cloud_logging]
    propagate: no
  production:
    level: INFO
    handlers: [cloud_logging]
    propagate: no
#  default:
#    level: INFO
#    handlers: [ cloud_logging ]
#    propagate: no
# Root LoggerはTraceログのみ有効とする
root:
  level: DEBUG
  handlers: [console]