[tool.poetry]
name = "python_logger_core_sample1"
version = "0.1.18"
description = ""
authors = ["Masashi.Kayahara <masashi.kayahara@arc-connects.com>"]

packages = [
    { include = "masakaya" },
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
