[tool.poetry]
name = "python_logger_core_sample"
version = "0.1.4"
description = ""
authors = ["Masashi.Kayahara <masashi.kayahara@arc-connects.com>"]

packages = [
    { include = "cs" },
]

[tool.poetry.dependencies]
python = "^3.10"
google-cloud-logging = ">=3.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
